const TEXT_DATA = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra tellus in hac habitasse platea dictumst vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Ut morbi tincidunt augue interdum. Sollicitudin aliquam ultrices sagittis orci a. Tortor consequat id porta nibh venenatis cras sed felis eget. Mi proin sed libero enim. Maecenas volutpat blandit aliquam etiam erat velit. Eros donec ac odio tempor orci dapibus ultrices in iaculis. Amet facilisis magna etiam tempor orci. Et malesuada fames ac turpis egestas maecenas. Scelerisque eleifend donec pretium vulputate sapien nec sagittis. Dictum at tempor commodo ullamcorper a lacus vestibulum. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Ultrices in iaculis nunc sed augue lacus viverra. Dignissim suspendisse in est ante in. Feugiat nisl pretium fusce id velit ut tortor pretium viverra.

Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Mauris cursus mattis molestie a iaculis. Duis tristique sollicitudin nibh sit. Tortor consequat id porta nibh venenatis cras sed. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Donec pretium vulputate sapien nec sagittis aliquam. Ultrices gravida dictum fusce ut placerat. Sagittis eu volutpat odio facilisis. Cum sociis natoque penatibus et. Odio eu feugiat pretium nibh ipsum consequat nisl vel. Egestas purus viverra accumsan in nisl nisi scelerisque eu. Scelerisque eu ultrices vitae auctor eu augue. Tempor orci eu lobortis elementum nibh tellus.

Fringilla urna porttitor rLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing enim eu turpis egestas pretium aenean pharetra magna. Ac felis donec et odio pellentesque diam volutpat commodo. At auctor urna nunc id cursus metus. Turpis egestas maecenas pharetra convallis posuere morbi leo. Velit egestas dui id ornare. Pretium fusce id velit ut. Interdum velit euismod in pellentesque massa. Lacus viverra vitae congue eu consequat ac felis donec et. Malesuada bibendum arcu vitae elementum.

Massa placerat duis ultricies lacus sed. Cursus eget nunc scelerisque viverra mauris in. Eu consequat ac felis donec. Convallis posuere morbi leo urna molestie. Sit amet porttitor eget dolor morbi non arcu. Elementum integer enim neque volutpat ac tincidunt vitae semper. In nisl nisi scelerisque eu ultrices. Orci dapibus ultrices in iaculis. Vel eros donec ac odio. Pellentesque id nibh tortor id aliquet lectus proin. Non arcu risus quis varius quam quisque id. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Purus faucibus ornare suspendisse sed. Aenean pharetra magna ac placerat vestibulum. Ultrices neque ornare aenean euismod elementum nisi.

Viverra justo nec ultrices dui sapien eget mi proin. Consectetur a erat nam at lectus urna duis. Aliquet eget sit amet tellus cras. Elit ut aliquam purus sit amet. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. Tempus quam pellentesque nec nam aliquam sem et. Porttitor rhoncus dolor purus non enim praesent elementum. Erat imperdiet sed euismod nisi porta. Egestas egestas fringilla phasellus faucibus. Platea dictumst quisque sagittis purus sit. Arcu dictum varius duis at consectetur lorem donec massa sapien. Ornare massa eget egestas purus viverra accumsan. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Ultricies leo integer malesuada nunc vel risus commodo viverra. Sed cras ornare arcu dui vivamus. Viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat. Orci eu lobortis elementum nibh tellus molestie nunc. Sed viverra tellus in hac. Lorem donec massa sapien faucibus et molestie ac feugiat. In est ante in nibh.

A scelerisque purus semper eget duis at tellus at urna. Nibh sed pulvinar proin gravida hendrerit lectus a. Viverra suspendisse potenti nullam ac tortor. Duis at consectetur lorem donec massa sapien. Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Odio morbi quis commodo odio aenean sed adipiscing. Odio pellentesque diam volutpat commodo sed. Ut eu sem integer vitae. Adipiscing diam donec adipiscing tristique risus nec feugiat in. Sit amet porttitor eget dolor. Scelerisque in dictum non consectetur a erat nam. Sed vulputate mi sit amet mauris. Tristique magna sit amet purus gravida quis blandit turpis cursus. Diam quam nulla porttitor massa id neque aliquam. Convallis posuere morbi leo urna molestie at. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Congue nisi vitae suscipit tellus mauris a. A pellentesque sit amet porttitor eget dolor morbi.

Dolor morbi non arcu risus quis varius quam quisque. Turpis egestas maecenas pharetra convallis posuere morbi leo. Auctor elit sed vulputate mi sit amet. Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Nisi quis eleifend quam adipiscing vitae. Posuere lorem ipsum dolor sit. Habitant morbi tristique senectus et netus. Elementum tempus egestas sed sed. Aliquam etiam erat velit scelerisque in. Urna et pharetra pharetra massa. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Vestibulum mattis ullamcorper velit sed ullamcorper. Egestas erat imperdiet sed euismod nisi porta lorem. Augue lacus viverra vitae congue eu. Egestas sed sed risus pretium quam.`;